
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://test_user:test_password@db:5432/test_db
    volumes:
      - /home/alexander/PycharmProjects/hillel_AQA/allure-results:/app/allure-results
      - /home/alexander/PycharmProjects/hillel_AQA/allure-report:/app/allure-report